export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/tech-managers/index',
    'pages/publish/index',
    'pages/messages/index',
    'pages/me/index',
  ],
  lazyCodeLoading: 'requiredComponents',
  subPackages: [
    {
      root: 'subpackages',
      pages: [
        'search/index',
        'patent-map/index',
        'patent-map/region-detail/index',
        'patent/detail/index',
        'patent/detail/summary/index',
        'patent/detail/info/index',
        'patent/detail/comments/index',
        'orders/index',
        'orders/detail/index',
        'checkout/deposit-pay/index',
        'checkout/deposit-success/index',
        'checkout/final-pay/index',
        'checkout/final-success/index',
        'publish/patent/index',
        'publish/demand/index',
        'publish/achievement/index',
        'publish/artwork/index',
        'messages/chat/index',
        'support/index',
        'support/faq/index',
        'support/faq/detail/index',
        'support/contact/index',
        'legal/privacy/index',
        'legal/terms/index',
        'legal/privacy-guide/index',
        'onboarding/choose-identity/index',
        'onboarding/verification-form/index',
        'notifications/index',
        'notifications/detail/index',
        'announcements/index',
        'announcements/detail/index',
        'listing/detail/index',
        'demand/detail/index',
        'achievement/detail/index',
        'artwork/detail/index',
        'favorites/index',
        'organizations/index',
        'organizations/detail/index',
        'inventors/index',
        'tech-managers/detail/index',
        'trade-rules/index',
        'contracts/index',
        'invoices/index',
        'addresses/index',
        'addresses/edit/index',
        'my-listings/index',
        'my-demands/index',
        'my-achievements/index',
        'my-artworks/index',
        'cluster-picker/index',
        'settings/notifications/index',
        'about/index',
        'profile/edit/index',
        'login/index',
        'region-picker/index',
        'ipc-picker/index',
      ],
    },
  ],
  window: {
    backgroundColor: '#f7f3ec',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'Ipmoney',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#475569',
    selectedColor: '#ff6600',
    backgroundColor: '#ffffff',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/tech-managers/index',
        text: '咨询',
        iconPath: 'assets/tabbar/consult.png',
        selectedIconPath: 'assets/tabbar/consult-active.png',
      },
      {
        pagePath: 'pages/publish/index',
        text: '发布',
        iconPath: 'assets/tabbar/publish.png',
        selectedIconPath: 'assets/tabbar/publish-active.png',
      },
      {
        pagePath: 'pages/messages/index',
        text: '消息',
        iconPath: 'assets/tabbar/messages.png',
        selectedIconPath: 'assets/tabbar/messages-active.png',
      },
      {
        pagePath: 'pages/me/index',
        text: '我的',
        iconPath: 'assets/tabbar/me.png',
        selectedIconPath: 'assets/tabbar/me-active.png',
      },
    ],
  },
});
