export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/patent-map/index',
    'pages/patent-map/region-detail/index',
    'pages/search/index',
    'pages/inventors/index',
    'pages/tech-managers/index',
    'pages/tech-managers/detail/index',
    'pages/organizations/index',
    'pages/organizations/detail/index',
    'pages/artwork/detail/index',
    'pages/listing/detail/index',
    'pages/listing/detail/summary/index',
    'pages/listing/detail/info/index',
    'pages/listing/detail/comments/index',
    'pages/demand/detail/index',
    'pages/demand/detail/summary/index',
    'pages/demand/detail/info/index',
    'pages/demand/detail/comments/index',
    'pages/achievement/detail/index',
    'pages/achievement/detail/summary/index',
    'pages/achievement/detail/info/index',
    'pages/achievement/detail/comments/index',
    'pages/patent/detail/index',
    'pages/patent/detail/summary/index',
    'pages/patent/detail/info/index',
    'pages/patent/detail/comments/index',
    'pages/trade-rules/index',
    'pages/favorites/index',
    'pages/orders/index',
    'pages/orders/detail/index',
    'pages/contracts/index',
    'pages/invoices/index',
    'pages/checkout/deposit-pay/index',
    'pages/checkout/deposit-success/index',
    'pages/checkout/final-pay/index',
    'pages/checkout/final-success/index',
    'pages/publish/index',
    'pages/my-listings/index',
    'pages/my-demands/index',
    'pages/my-achievements/index',
    'pages/my-artworks/index',
    'pages/publish/patent/index',
    'pages/publish/demand/index',
    'pages/publish/achievement/index',
    'pages/publish/artwork/index',
    'pages/messages/index',
    'pages/messages/chat/index',
    'pages/notifications/index',
    'pages/notifications/detail/index',
    'pages/announcements/index',
    'pages/announcements/detail/index',
    'pages/cluster-picker/index',
    'pages/me/index',
    'pages/settings/notifications/index',
    'pages/settings/security/index',
    'pages/about/index',
    'pages/support/index',
    'pages/support/faq/index',
    'pages/legal/privacy/index',
    'pages/legal/terms/index',
    'pages/legal/privacy-guide/index',
    'pages/profile/edit/index',
    'pages/login/index',
    'pages/onboarding/choose-identity/index',
    'pages/onboarding/verification-form/index',
    'pages/region-picker/index',
    'pages/ipc-picker/index',
  ],
  window: {
    backgroundColor: '#f7f3ec',
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#ffffff',
    navigationBarTitleText: 'Ipmoney',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#475569',
    selectedColor: '#ff6600',
    backgroundColor: '#ffffff',
    list: [
      {
        pagePath: 'pages/home/index',
        text: '首页',
        iconPath: 'assets/tabbar/home.png',
        selectedIconPath: 'assets/tabbar/home-active.png',
      },
      {
        pagePath: 'pages/tech-managers/index',
        text: '咨询',
        iconPath: 'assets/tabbar/consult.png',
        selectedIconPath: 'assets/tabbar/consult-active.png',
      },
      {
        pagePath: 'pages/publish/index',
        text: '发布',
        iconPath: 'assets/tabbar/publish.png',
        selectedIconPath: 'assets/tabbar/publish-active.png',
      },
      {
        pagePath: 'pages/messages/index',
        text: '消息',
        iconPath: 'assets/tabbar/messages.png',
        selectedIconPath: 'assets/tabbar/messages-active.png',
      },
      {
        pagePath: 'pages/me/index',
        text: '我的',
        iconPath: 'assets/tabbar/me.png',
        selectedIconPath: 'assets/tabbar/me-active.png',
      },
    ],
  },
});
